'use strict';
const $=id=>document.getElementById(id), board=$('board');
let cols=12,rows=7,cells=[],playing=false,score=0,combo=1,lastSuccess=0,endAt=0,ticker=null,anchor=null,dragging=false,dragMoved=false,press=null,selected=[],feedbackTimer=null;
function rect(a,b){let ids=[];for(let r=Math.floor(Math.min(Math.floor(a/cols),Math.floor(b/cols)));r<=Math.max(Math.floor(a/cols),Math.floor(b/cols));r++)for(let c=Math.min(a%cols,b%cols);c<=Math.max(a%cols,b%cols);c++)ids.push(r*cols+c);return ids;}
function findMove(){for(let top=0;top<rows;top++)for(let left=0;left<cols;left++)for(let bottom=top;bottom<rows;bottom++){let total=0;for(let right=left;right<cols;right++){for(let r=top;r<=bottom;r++)total+=cells[r*cols+right]?.n||0;if(total===10)return [top*cols+left,bottom*cols+right];if(total>10)break;}}return null;}
function makeBoard(){cells=Array.from({length:cols*rows},()=>({n:1+Math.floor(Math.random()*9),type:'normal'}));cells[0].n=3;cells[1].n=7;for(let i=2;i<cells.length;i++){const p=Math.random();cells[i].type=p<.065?'gold':p<.115?'bomb':'normal';}render();}
function render(){board.innerHTML='';cells.forEach((cell,i)=>{const b=document.createElement('button');b.className='cell '+(cell?cell.type:'empty');b.dataset.index=i;b.type='button';b.setAttribute('aria-label',cell?`${Math.floor(i/cols)+1}행 ${i%cols+1}열, ${cell.type==='gold'?'황금 사과':cell.type==='bomb'?'폭탄':'사과'} ${cell.n}`:'빈칸');if(cell){b.innerHTML=`<span class="fruit">${cell.type==='bomb'?'💣':'🍎'}</span><span class="number">${cell.n}</span>`;}b.addEventListener('keydown',e=>{if(!playing)return;let next=i;if(e.key==='ArrowRight')next=Math.min(cells.length-1,i+1);else if(e.key==='ArrowLeft')next=Math.max(0,i-1);else if(e.key==='ArrowDown')next=Math.min(cells.length-1,i+cols);else if(e.key==='ArrowUp')next=Math.max(0,i-cols);else if(e.key==='Enter'||e.key===' '){e.preventDefault();tap(i);return;}else return;e.preventDefault();board.children[next].focus();});board.appendChild(b);});}
function updateSelection(a,b){selected=rect(a,b);const set=new Set(selected);[...board.children].forEach((el,i)=>el.classList.toggle('selected',set.has(i)));const total=selected.reduce((s,i)=>s+(cells[i]?.n||0),0);$('sum').textContent=total;document.querySelector('.sum-pill').classList.toggle('good',total===10);}
function clearSelection(){anchor=null;selected=[];$('sum').textContent=0;document.querySelector('.sum-pill').classList.remove('good');[...board.children].forEach(el=>el.classList.remove('selected'));}
function message(t){clearTimeout(feedbackTimer);$('status').textContent=t;}
function resolve(){if(!playing||Date.now()>=endAt){finish();return;}const total=selected.reduce((s,i)=>s+(cells[i]?.n||0),0);if(total!==10){combo=1;$('combo').textContent='×1';message(`합계 ${total}! 10을 찾아봐.`);clearSelection();return;}const now=Date.now();combo=lastSuccess&&now-lastSuccess<=4000?Math.min(combo+1,4):1;lastSuccess=now;const removed=new Set(selected.filter(i=>cells[i]));const queue=[...removed];for(let q=0;q<queue.length;q++){const i=queue[q];if(cells[i]?.type!=='bomb')continue;const r=Math.floor(i/cols),c=i%cols;for(let y=Math.max(0,r-1);y<=Math.min(rows-1,r+1);y++)for(let x=Math.max(0,c-1);x<=Math.min(cols-1,c+1);x++){const j=y*cols+x;if(cells[j]&&!removed.has(j)){removed.add(j);queue.push(j);}}}const gold=[...removed].filter(i=>cells[i].type==='gold').length;const bomb=[...removed].some(i=>cells[i].type==='bomb');const points=removed.size*10*combo+gold*50;score+=points;removed.forEach(i=>{cells[i]=null;});$('score').textContent=score;$('combo').textContent='×'+combo;message(`${bomb?'💥 폭발! ':gold?'✨ 황금 수확! ':'좋아! '}${removed.size}개 수확 · +${points}점`);clearSelection();render();removed.forEach(i=>board.children[i].classList.add('burst'));if(!findMove()){makeBoard();message(`+${points}점! 움직임이 없어 새 사과가 도착했어.`);}}
function tap(i){if(!playing)return;if(anchor===null){anchor=i;updateSelection(i,i);message('반대쪽 모서리를 눌러 선택을 완성해!');}else{updateSelection(anchor,i);resolve();}}
function atPoint(e){const el=document.elementFromPoint(e.clientX,e.clientY)?.closest('.cell');return el&&board.contains(el)?Number(el.dataset.index):null;}
board.addEventListener('pointerdown',e=>{if(!playing||e.button!==0)return;const i=atPoint(e);if(i===null)return;e.preventDefault();press=i;dragging=true;dragMoved=false;board.setPointerCapture(e.pointerId);updateSelection(anchor??i,i);});
board.addEventListener('pointermove',e=>{if(!dragging)return;const i=atPoint(e);if(i===null)return;if(i!==press)dragMoved=true;updateSelection(anchor??press,i);});
board.addEventListener('pointerup',e=>{if(!dragging)return;dragging=false;if(board.hasPointerCapture(e.pointerId))board.releasePointerCapture(e.pointerId);const i=atPoint(e);if(dragMoved){if(i!==null)updateSelection(anchor??press,i);resolve();}else if(i!==null){tap(i);}else clearSelection();press=null;});
board.addEventListener('pointercancel',()=>{dragging=false;press=null;clearSelection();});
function tick(){if(!playing)return;const seconds=Math.max(0,(endAt-Date.now())/1000);$('time').textContent=Math.ceil(seconds);$('timebar').style.width=(seconds/60*100)+'%';document.body.classList.toggle('frenzy',seconds<=10);if(seconds<=0)finish();else if(lastSuccess&&Date.now()-lastSuccess>4000&&combo>1){combo=1;$('combo').textContent='×1';}}
function start(){clearInterval(ticker);clearTimeout(feedbackTimer);cols=matchMedia('(max-width:640px)').matches?8:12;rows=cols===8?9:7;board.style.gridTemplateColumns=`repeat(${cols},minmax(0,1fr))`;playing=true;score=0;combo=1;lastSuccess=0;anchor=null;dragging=false;selected=[];$('score').textContent='0';$('combo').textContent='×1';$('sum').textContent='0';$('time').textContent='60';$('timebar').style.width='100%';document.body.classList.remove('frenzy');document.querySelector('.sum-pill').classList.remove('good');$('overlay').classList.add('hidden');$('start').innerHTML='다시 시작 <span>↻</span>';makeBoard();endAt=Date.now()+60000;message('사과를 드래그해 합계 10을 만들어봐!');ticker=setInterval(tick,100);}
function finish(){if(!playing)return;playing=false;dragging=false;clearInterval(ticker);clearSelection();$('time').textContent='0';$('timebar').style.width='0%';$('overlay-title').textContent=`${score.toLocaleString()}점 수확!`;$('overlay-copy').textContent='멋진 수확이었어. 한 번 더 도전해볼까?';$('overlay-start').textContent='다시 플레이';$('overlay').classList.remove('hidden');$('start').innerHTML='다시 시작 <span>↻</span>';message('시간 종료! 다시 플레이해봐.');}
$('start').addEventListener('click',start);$('overlay-start').addEventListener('click',start);document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick();});cols=matchMedia('(max-width:640px)').matches?8:12;rows=cols===8?9:7;board.style.gridTemplateColumns=`repeat(${cols},minmax(0,1fr))`;makeBoard();
